services:
  - type: web
    name: campus-shoppy
    env: python
    plan: free
    buildCommand: |
      echo "Starting build with pip..."
      pip install --upgrade pip
      pip install -r requirements.txt
      python manage.py migrate
      python manage.py collectstatic --noinput
      echo "Build completed successfully!"
    startCommand: gunicorn django_ecommerce.wsgi:application --bind 0.0.0.0:$PORT
    pythonVersion: 3.11.10
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: false
      - key: RENDER_EXTERNAL_HOSTNAME
        fromService:
          type: web
          name: campus-shoppy
          property: host
      - key: DATABASE_URL
        fromDatabase:
          name: campus-shoppy-db
          property: connectionString
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: PAYSTACK_SECRET_KEY
        sync: false
      - key: PAYSTACK_PUBLIC_KEY
        sync: false
      - key: MPESA_CONSUMER_KEY
        sync: false
      - key: MPESA_CONSUMER_SECRET
        sync: false
      - key: MPESA_SHORTCODE
        sync: false
      - key: MPESA_PASSKEY
        sync: false
      - key: MPESA_BASE_URL
        value: https://sandbox.safaricom.co.ke
      - key: MPESA_CALLBACK_URL
        value: https://campus-shoppy.onrender.com/payments/callback/

databases:
  - name: campus-shoppy-db
    plan: free
