services:
  - type: web
    name: campus-shoppy
    env: python
    plan: free
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt && python manage.py migrate
    startCommand: gunicorn django_ecommerce.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: campus-shoppy-maseno-7y1e.onrender.com,*.onrender.com
      - key: PAYSTACK_SECRET_KEY
        sync: false
      - key: PAYSTACK_PUBLIC_KEY
        sync: false
      - key: PAYSTACK_CALLBACK_URL
        value: https://campus-shoppy-maseno-7y1e.onrender.com/payments/paystack/callback/